[package]
name = "foxess"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13", features = ["query", "form"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
chrono = {  version = "0.4", features = ["serde"] }
md-5 = "0.10.6"

[dev-dependencies]
tokio = { version = "1.49", features = ["macros", "rt"] }