[package]
name = "foxess"
version = "0.2.0"
edition = "2024"

[features]
default = ["async"]
async = ["dep:reqwest"]
blocking = ["dep:reqwest", "reqwest/blocking"]

[dependencies]
reqwest = { version = "0.13", default-features = false, features = ["query", "form", "rustls"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
chrono = {  version = "0.4", features = ["serde"] }
md-5 = "0.10.6"

[dev-dependencies]
tokio = { version = "1.49", features = ["macros", "rt"] }
httpmock = "0.8"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
