//! This module hosts variable enumerations, specifications, and associated traits.
//! The [FoxVariables] enumeration is mainly used when requesting several values from FoxESS cloud at once.
//!
//! The [VariableSpec] is implemented for marker structs to be used together with typed get functions.
//!
//! FoxESS Cloud currently supports many variables, end the foxess crate implements only a subset from them.
//!
//!

use std::str::FromStr;
use crate::FoxError;

const PV_POWER: &str = "pvPower";
const LOADS_POWER: &str = "loadsPower";
const SOC: &str = "SoC";
const SOH: &str = "SOH";
const BAT_TEMPERATURE: &str = "batTemperature";

/// An enumeration representing the available real-time variables from FoxESS cloud.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FoxVariables {
    /// The power generated by the photovoltaic panels.
    PvPower,
    /// The current electrical load on the system.
    LoadsPower,
    /// The State of Charge (SoC) of the battery.
    SoC,
    /// The State of Health (SoH) of the battery.
    SoH,
    /// The current temperature of the battery.
    BatTemperature,
}

impl FoxVariables {
    /// Returns the string representation of the `FoxVariables` enum variant.
    ///
    /// This string matches the key used by the FoxESS cloud API.
    ///
    /// # Returns
    /// * `&'static str` - The string representation of the variable.
    pub const fn as_str(&self) -> &'static str {
        match self {
            FoxVariables::PvPower => PV_POWER,
            FoxVariables::LoadsPower => LOADS_POWER,
            FoxVariables::SoC => SOC,
            FoxVariables::SoH => SOH,
            FoxVariables::BatTemperature => BAT_TEMPERATURE,
        }
    }
}
impl FromStr for FoxVariables {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            PV_POWER => Ok(FoxVariables::PvPower),
            LOADS_POWER => Ok(FoxVariables::LoadsPower),
            SOC => Ok(FoxVariables::SoC),
            SOH => Ok(FoxVariables::SoH),
            BAT_TEMPERATURE => Ok(FoxVariables::BatTemperature),
            _ => Err(()),
        }
    }
}

/// A trait defining the specification for a FoxESS variable.
///
/// Types implementing this trait define how to convert a raw floating-point value
/// from the API into a specific Rust type.
pub trait VariableSpec {
    /// The Rust type that the variable value will be converted into.
    type Value;
    /// The `FoxVariables` variant associated with this specification.
    const VARIABLE: FoxVariables;
    /// Converts the raw `f64` value into the associated `Value` type.
    ///
    /// # Arguments
    /// * `raw` - The raw `f64` value received from the FoxESS API.
    ///
    /// # Returns
    /// * `Result<Self::Value, FoxError>` - The converted value or an error if conversion fails.
    fn into(raw: f64) -> Result<Self::Value, FoxError>;
}

/// Specification for the `PvPower` variable.
pub struct PvPower;
impl VariableSpec for PvPower {
    type Value = f64;
    const VARIABLE: FoxVariables = FoxVariables::PvPower;

    fn into(raw: f64) -> Result<Self::Value, FoxError> {
        Ok(raw)
    }
}

/// Specification for the `LoadsPower` variable.
pub struct LoadsPower;
impl VariableSpec for LoadsPower {
    type Value = f64;
    const VARIABLE: FoxVariables = FoxVariables::LoadsPower;
    fn into(raw: f64) -> Result<Self::Value, FoxError> {
        Ok(raw)
    }
}

/// Specification for the `SoC` variable.
pub struct SoC;
impl VariableSpec for SoC {
    type Value = u8;
    const VARIABLE: FoxVariables = FoxVariables::SoC;

    fn into(raw: f64) -> Result<Self::Value, FoxError> {
        try_f64_to_u8_percentage(raw).map_err(|e| FoxError::VariableConversionError {
            variable: Self::VARIABLE.as_str(),
            value: raw.to_string(),
            error: e.to_string(),
        })
    }
}

/// Specification for the `SoH` variable.
pub struct SoH;
impl VariableSpec for SoH {
    type Value = u8;
    const VARIABLE: FoxVariables = FoxVariables::SoH;

    fn into(raw: f64) -> Result<Self::Value, FoxError> {
        try_f64_to_u8_percentage(raw).map_err(|e| FoxError::VariableConversionError {
            variable: Self::VARIABLE.as_str(),
            value: raw.to_string(),
            error: e.to_string(),
        })
    }
}

/// Specification for the `BatTemperature` variable.
pub struct BatTemperature;
impl VariableSpec for BatTemperature {
    type Value = f64;
    const VARIABLE: FoxVariables = FoxVariables::BatTemperature;

    fn into(raw: f64) -> Result<Self::Value, FoxError> {
        Ok(raw)
    }
}

/// Attempts to convert a floating-point value to an 8-bit unsigned integer percentage.
///
/// The value is rounded to the nearest integer and checked to be in the range [0, 100].
///
/// # Arguments
/// * `x` - The raw floating-point value.
///
/// # Returns
/// * `Result<u8, &'static str>` - The converted percentage or an error if the value is invalid.
fn try_f64_to_u8_percentage(x: f64) -> Result<u8, &'static str> {
    if !x.is_finite() {
        return Err("value is NaN or infinite");
    }

    let y = x.round(); // ties-to-even (banker's rounding)

    if !(0.0..=100.0).contains(&y) {
        return Err("value out of range for u8 percentage after rounding");
    }

    Ok(y as u8)
}